# -*- coding: utf-8 -*-
r"""EEE 202 — TOPIC METADATA with summaryNotes (study/notes drawer content).
summaryNotes uses $...$ inline math and $$...$$ block math, rendered by KaTeX.r"""

TOPICS = [
{
"id": "eee-magnetism",
"name": "Magnetism & Moving Charges",
"summaryNotes": r"""
### Key Abstractions & Principles
- Magnetism is the force produced by moving charges; it attracts or repels other magnets and moving charges. Like poles repel; unlike poles attract.
- A magnetic field is the region around a magnet (or current-carrying conductor) where magnetic force is observable. Field lines never cross, form closed loops, and repel one another when parallel.
- The B-field is the field defined by the force it exerts on a moving charged particle (unit tesla, T; $1\ T = 10^4$ gauss). The H-field is the field within a material (unit ampere/metre, A/m).
- Ferromagnetic materials (e.g. magnetite, $Fe_3O_4$ — the first known magnet) have electron magnets that do not cancel.
- An electromagnet is a temporary magnet: a coil wound on a soft-iron core (solenoid) energised by a current.

### Core Mathematical Relations
- $F = qvB\sin\theta$ : force on a charge $q$ moving at velocity $v$ across field $B$ at angle $\theta$ between $v$ and $B$. Parallel motion ($\theta = 0$) gives $F = 0$.
- $F = BIl\sin\theta$ : force on a straight conductor of length $l$ carrying current $I$ in field $B$.
- $B = \mu_0 n I$ : field at the centre of a solenoid, where $n = N/L$ is the turns per metre and $\mu_0 = 4\pi\times10^{-7}$ T·m/A.
- $E = Blv$ : motional e.m.f. of a conductor of length $l$ cutting flux at speed $v$ at right angles to $B$.

### Common Pitfalls & Exam Traps
- Trap 1: Taking $\theta$ as the angle of travel instead of the angle BETWEEN $v$ and $B$.
- Trap 2: Forgetting that $\sin 0^\circ = 0$ and $\sin 90^\circ = 1$ — the "charge moving parallel to the field" case is a favourite.
- Trap 3: In solenoids, using the total turns $N$ instead of $n = N/L$ — this overstates $B$ by the factor $L$.
r"""
},
{
"id": "eee-induction",
"name": "Electromagnetic Induction & Faraday's Laws",
"summaryNotes": r"""
### Key Abstractions & Principles
- Electromotive force (e.m.f.) is that which tends to produce an electric current in a circuit; symbol E, unit volt (V).
- Principal sources of e.m.f.: electrodes in an electrolyte (cells), relative motion of a conductor and magnetic flux (generators), and temperature difference at thermo-junctions.
- Faraday's 1st Law: an e.m.f. is induced in a conductor whenever it is placed in a changing magnetic field; a current flows if the circuit is closed.
- Faraday's 2nd Law: the magnitude of the induced e.m.f. equals the rate of change of flux linkage.
- Lenz's Law: the induced effect opposes the change producing it (this is the minus sign).
- Eddy (Foucault) currents: loops induced in bulk conductors by changing fields; they oppose the change and are exploited/fought in transformers and machines.

### Core Mathematical Relations
- $E = N\frac{d\Phi}{dt}$ : induced e.m.f. in an N-turn coil (instantaneous form).
- $E = N\frac{\Delta\Phi}{\Delta t}$ : uniform-change form — use for "flux changes from $\Phi_1$ to $\Phi_2$ in $t$ seconds" problems.
- $\Phi = BA$ : magnetic flux through area $A$ in field $B$.
- $I = \frac{E}{R}$ : induced current, from the coil resistance (Ohm's law).

### Common Pitfalls & Exam Traps
- Trap 1: Dropping $N$ — e.m.f. scales with the number of turns; single-loop problems use $N = 1$.
- Trap 2: Writing $\Delta\Phi$ backwards — always initial flux minus final flux.
- Trap 3: Reporting the Lenz minus sign as a numerical answer — it only gives direction; magnitudes are positive.
r"""
},
{
"id": "eee-ac-phasors",
"name": "AC Waveforms & Phasors",
"summaryNotes": r"""
### Key Abstractions & Principles
- Direct current (DC) is uni-directional and constant in time. Alternating current (AC) varies in both magnitude and direction — the sinusoid $A(t) = A_m\sin(2\pi ft)$.
- Period $T$ = time for one full cycle (s). Frequency $f$ = cycles per second (Hz), and $f = 1/T$. Angular frequency $\omega = 2\pi f$ (rad/s).
- Peak, r.m.s. and average: $V_{rms} = V_m/\sqrt{2} = 0.707V_m$; half-cycle average $= 0.637V_m$; $V_m = 1.414V_{rms}$.
- A phasor is a rotating vector (magnitude + phase) representing a sinusoid; Charles Steinmetz (General Electric, 1893) formalised the symbolic method. Phasors add like vectors.
- AC cannot be stored in batteries or cells; it is generated by alternators/waveform generators.

### Core Mathematical Relations
- $X_L = 2\pi f L$ : inductive reactance (Ω) — rises with frequency.
- $X_C = \frac{1}{2\pi f C}$ : capacitive reactance (Ω) — falls with frequency.
- $Z = R + jX_L$ (inductive) or $Z = R - jX_C$ (capacitive); magnitude $|Z| = \sqrt{R^2 + X^2}$.
- $T = \frac{1}{f}$, $f = \frac{1}{T}$, $\omega = 2\pi f$.

### Common Pitfalls & Exam Traps
- Trap 1: Mixing r.m.s. and peak — always state which one you are reporting.
- Trap 2: Writing $|Z| = R + X$ — reactances combine with resistance in quadrature (square root of the sum of squares).
- Trap 3: Unit slip — frequency in Hz, period in seconds (20 ms = 0.02 s), C in farads ($10\ \mu F = 10^{-5}\ F$).
r"""
},
{
"id": "eee-resonance",
"name": "Resonance in AC Circuits",
"summaryNotes": r"""
### Key Abstractions & Principles
- Series resonance: the condition $X_L = X_C$; the impedance is then a MINIMUM ($Z = R$) and the current a MAXIMUM; the power factor is unity because the circuit is purely resistive.
- Parallel resonance (anti-resonance): the parallel L-C combination presents a MAXIMUM impedance; the supply (line) current is a minimum.
- The quality factor Q measures the sharpness/selectivity of resonance — high Q gives a narrow bandwidth.

### Core Mathematical Relations
- $f_0 = \frac{1}{2\pi\sqrt{LC}}$ : resonant frequency (from $2\pi f L = 1/(2\pi f C)$).
- $Q = \frac{X_L}{R} = \frac{X_C}{R}$ : Q factor at resonance.
- Bandwidth $= \frac{f_0}{Q}$.
- At resonance, $X_L = X_C = 2\pi f_0 L$.

### Common Pitfalls & Exam Traps
- Trap 1: Forgetting the square root of $LC$ before taking the reciprocal.
- Trap 2: Unit mix-ups — L in henrys, C in farads ($1\ \mu F = 10^{-6}\ F$).
- Trap 3: Reversing the series/parallel duality — minimum impedance in series resonance, maximum in parallel.
r"""
},
{
"id": "eee-network-theorems",
"name": "Network Theorems Applied to AC",
"summaryNotes": r"""
### Key Abstractions & Principles
- Thévenin's theorem: any linear two-terminal network is equivalent to one voltage source (the open-circuit voltage $V_{th}$) in SERIES with the equivalent impedance $Z_{th}$.
- Norton's theorem: the dual form — a current source (the short-circuit current $I_N$) in PARALLEL with $Z_N = Z_{th}$.
- Superposition: the response in any branch is the algebraic sum of the responses produced by each source acting alone (voltage sources replaced by shorts, current sources by opens).
- For AC networks the impedances are complex ($R \pm jX$); the j-terms must be carried through every line so phase is preserved.
- Linearity is judged by the i-v graph: a straight line is linear; $y = x^2$ and $y = |x|$ (piecewise linear) are nonlinear. The negative-resistance converter is a key nonlinear op-amp circuit that enables oscillators.

### Core Mathematical Relations
- Series: $Z_{eq} = Z_1 + Z_2$; Parallel: $Z_{eq} = \frac{Z_1 Z_2}{Z_1 + Z_2}$ (two equal impedances give $Z/2$).
- $|Z| = \sqrt{R^2 + X^2}$.
- Load current: $I = \frac{V_{th}}{Z_{th} + Z_{load}}$.

### Common Pitfalls & Exam Traps
- Trap 1: Using only magnitudes (dropping j) — phase information is lost.
- Trap 2: Forgetting that equal parallel impedances halve, and misapplying the product/sum formula.
- Trap 3: Killing sources wrongly in superposition — voltage sources become short circuits, current sources become open circuits.
r"""
},
{
"id": "eee-magcircuits-transformer",
"name": "Magnetic Circuits & Transformers",
"summaryNotes": r"""
### Key Abstractions & Principles
- The magnetic circuit is the flux analogue of the electric circuit: magnetomotive force (m.m.f.) drives flux through reluctance, exactly as e.m.f. drives current through resistance.
- Analogy table: electric flux $\leftrightarrow$ magnetic flux; $D \leftrightarrow B$; $E \leftrightarrow H$; e.m.f. $\leftrightarrow$ m.m.f.; permittivity $\leftrightarrow$ permeability.
- Ideal transformer: $V_1/V_2 = N_1/N_2 = I_2/I_1$ (power in = power out). Step-up: $N_2 > N_1$; step-down: $N_2 < N_1$.
- Transformers operate only on AC: induction requires a CHANGING flux ($E = N d\Phi/dt$); steady DC produces zero secondary e.m.f.
- Practical losses: copper ($I^2R$) and iron (eddy current + hysteresis).

### Core Mathematical Relations
- $F = NI$ (ampere-turns); $H = \frac{F}{l} = \frac{NI}{l}$ (A/m); $B = \mu H$ (T); $\Phi = BA$ (Wb).
- Reluctance $S = \frac{l}{\mu A}$ (A/Wb); magnetic Ohm's law $\Phi = \frac{F}{S}$.
- $\mu_0 = 4\pi\times10^{-7}$ H/m; $\mu_r = \frac{\mu}{\mu_0}$; $\mu = \mu_0\mu_r$.
- $V_2 = V_1\frac{N_2}{N_1}$; $I_1 = I_2\frac{N_2}{N_1}$; $E = Blv$.

### Common Pitfalls & Exam Traps
- Trap 1: Using $\mu_0$ for a material instead of $\mu = \mu_0\mu_r$ ($\mu_r$ can be thousands).
- Trap 2: Inverting the transformer ratio — the smaller turn count always gets the smaller voltage.
- Trap 3: In $S = l/(\mu A)$, the $\mu A$ means permeability × area (not micro-amperes).
r"""
},
{
"id": "eee-motors-generators",
"name": "Electrical Motors & Generators",
"summaryNotes": r"""
### Key Abstractions & Principles
- A motor converts electrical energy into mechanical energy; a generator converts mechanical energy into electrical energy. Both are coupled through the magnetic field.
- Faraday (1831): a conductor moved in a magnetic field generates a current, and a current in a field develops force — the two directions of electromechanics.
- DC machine parts: armature (rotating windings where e.m.f. is generated), field system (produces flux), commutator (rectifies the armature AC into DC output), brushes.
- Fleming's LEFT-hand rule gives the motor force on a current-carrying conductor; the RIGHT-hand rule gives the generator's induced e.m.f.
- An AC generator is called an alternator; a battery is a stored-chemical-energy source while a generator produces e.m.f. from motion in a field.

### Core Mathematical Relations
- $E = Blv$ : motional e.m.f. (conductor moving perpendicular to $B$).
- $F = BIl$ : force on the armature conductor.

### Common Pitfalls & Exam Traps
- Trap 1: Swapping the left/right hand rules — LEFT = Motor (FBI), RIGHT = Generator.
- Trap 2: Applying $E = Blv$ without the perpendicularity condition ($v \perp B$).
- Trap 3: Reversing the energy-conversion directions in motor vs generator descriptions.
r"""
},
{
"id": "eee-instruments",
"name": "Instruments & Instrumentation",
"summaryNotes": r"""
### Key Abstractions & Principles
- Instrumentation = using devices (instruments) to detect, observe, measure, control, compute, communicate and display physical quantities. Instruments extend human senses: accurate, rapid measurement over great ranges.
- Ammeter: connected in SERIES and must have a very LOW resistance (it must not disturb the current being measured).
- Voltmeter: connected in PARALLEL and must have a very HIGH resistance (it must draw negligible current).
- PMMC (permanent-magnet moving coil): DC only, uniform scale, polarity matters. Moving iron: reads AC and DC (r.m.s.), robust, non-uniform scale.
- Indicating instruments are analog (pointer + scale) or digital (numeric display). Errors arise from movement friction and pointer parallax.

### Core Mathematical Relations
- Voltmeter conversion: total resistance $R_t = \frac{V}{I_{fsd}}$; series multiplier $= R_t - R_m$.
- Ammeter conversion: $I_m R_m = (I - I_m) R_{sh}$, so shunt $R_{sh} = \frac{I_m R_m}{I - I_m}$.

### Common Pitfalls & Exam Traps
- Trap 1: Putting the ammeter's shunt in series, or the voltmeter's multiplier in parallel — both ruin the instrument.
- Trap 2: Forgetting to subtract the movement resistance $R_m$ when computing the multiplier.
- Trap 3: Using the wrong branch current (movement current vs diverted current) in the shunt formula.
r"""
},
{
"id": "eee-nonlinear",
"name": "Nonlinear Circuits (Introduction)",
"summaryNotes": r"""
### Key Abstractions & Principles
- Linear ⇔ the i-v graph is a straight line ($v = Ri$). Nonlinear ⇔ any other i-v shape — a diode, $y = x^2$, even the piecewise-linear $y = |x|$ (it cannot be written as $y = ax + b$).
- Amplifiers, computers and most practical devices are built from nonlinear components — nonlinear analysis is "the real engineering".
- There are no hard-and-fast rules for most nonlinear circuits, but systematic methods exist for op-amp nonlinear circuits.
- The negative resistance converter is a key op-amp nonlinear circuit: its i-v slope is negative over a region, so it delivers power — which is exactly what an OSCILLATOR needs to sustain oscillations.

### Core Mathematical Relations
- Linear form: $y = ax + b$.
- Nonlinear examples: $y = x^2$ (parabola), $y = |x|$ (piecewise linear but not of the form $ax + b$).

### Common Pitfalls & Exam Traps
- Trap 1: Calling $|x|$ linear because its pieces are straight lines.
- Trap 2: Classifying a circuit by its components instead of by the shape of its i-v graph.
- Trap 3: Believing nonlinear circuits have no analysis methods at all (op-amp nonlinear circuits do).
r"""
},
]
