// ===========================================================================
// QUESTION BANK  —  CBT Lab 2 · Obafemi Awolowo University · EEE 282
// ---------------------------------------------------------------------------
// Generated by build_eee282_data.py. One course: EEE 282.
// Question fields:
//   type    : "mcq" | "calc" | "text"  (calc/text also render a typed answer box)
//   num     : { values: [...], unit }  numeric grader (all values must be matched)
//   match   : { all: [], any: [], minAny: {n, list} }  keyword grader for "text"
//   expected: the model typed answer shown in Study mode and Results
// ===========================================================================

export const courses = [
{
  "id": "eee282",
  "code": "EEE 282",
  "title": "Electronic & Electrical Introductory Practicals II",
  "blurb": "Practical-first preparation for the EEE 282 bench exam: active vs passive components and their symbols, transistor (BJT) type and pin identification with a digital multimeter, and CRO controls plus every waveform calculation (Vp-p, Vp, Vrms, period, frequency, phase and Lissajous). 30 questions \u2014 each with a diagram where it helps, a worked solution and distractor analysis.",
  "accent": "#010080",
  "available": true
},
]

export const categoryMeta = {}

export const topicMeta = {
  "eee282": [
    {
      "id": "active-passive",
      "name": "Active & Passive Components",
      "summaryNotes": "### Core rule\n- **Active** \u2014 needs an external supply; can control current or give power gain\n  (diode, zener, LED, BJT, MOSFET, op-amp, SCR).\n- **Passive** \u2014 cannot add energy; stores or dissipates it (R, L, C, potentiometer, LDR,\n  thermistor, transformer).\n\n### Components you must be able to draw and use\n- **Diode** \u2014 triangle (anode) into a bar (cathode); the **band** on the body marks the cathode.\n- **Zener** \u2014 diode with a **Z-shaped** cathode; works in **reverse breakdown** at $V_Z$; always\n  used with a series resistor.\n- **Potentiometer** \u2014 full track between pins **1 and 3**; wiper on **pin 2**;\n  $V_{out}=V_{in}\\frac{R_{2\\to3}}{R_{1\\to3}}$.\n- **NTC thermistor** \u2014 temperature up, resistance **down** (PTC is the opposite).\n- **LDR** \u2014 resistance **highest in darkness**, lowest in bright light.\n- **Electrolytic capacitor** \u2014 **polarised**; long lead positive, striped side negative.\n\n### Exam traps\n- Non-linear does **not** mean active (a thermistor is non-linear and passive).\n- Amplification always needs a supply \u2014 a passive network can only attenuate.\n- Fitting an electrolytic the wrong way round is the classic bench fault."
    },
    {
      "id": "bjt-diagnostics",
      "name": "BJT Pin & Type Diagnostics",
      "summaryNotes": "### The model\nA BJT is **two diodes sharing the base**:\n- **NPN** \u2014 the two **anodes** meet at the base.\n- **PNP** \u2014 the two **cathodes** meet at the base.\n\n### Identification routine (diode mode)\n1. Find the pin that shows a drop of **\u22480.6\u20130.7 V to both** other pins. That is the **base**.\n2. **Red probe on the base \u2192 NPN.** **Black probe on the base \u2192 PNP.**\n3. Split emitter from collector with the doping rule: $V_{BE} > V_{BC}$ by 5\u201315 mV.\n   **The larger reading is the emitter.**\n\n### Health checks\n- **C\u2013E reads `OL` both ways** \u2192 healthy (two opposing junctions).\n- **C\u2013E reads 0.000 V** \u2192 **shorted**, faulty.\n- **No drop on any combination** \u2192 **open**, faulty.\n- No single pin that conducts to both others \u2192 **not a BJT**.\n\n### Exam traps\n- The emitter/collector difference is only a few millivolts \u2014 write both readings down.\n- Test the transistor **out of circuit**.\n- Ohms mode usually cannot forward-bias a silicon junction; use **diode mode**."
    },
    {
      "id": "cro-controls",
      "name": "CRO Controls & Functions",
      "summaryNotes": "### The controls\n| Control | Axis | What it does |\n|---|---|---|\n| **Time/Div** (time base) | horizontal | seconds per horizontal division |\n| **Volts/Div** | vertical | volts per vertical division |\n| **Trigger / Level** | horizontal | stabilises a stationary trace |\n| **Vertical Position** | vertical | moves the trace up/down (no amplitude change) |\n| **Horizontal Position** | horizontal | slides the trace left/right |\n| **Focus / Intensity** | \u2014 | sharpness / brightness |\n| **Coupling (DC / AC / GND)** | \u2014 | pass everything / block DC / show the 0 V line |\n\n### The graticule\nOne **major division = 1 cm \u00d7 1 cm**; typical screen is **8 vertical \u00d7 10 horizontal** divisions,\neach subdivided into 5 minor ticks.\n\n### Set-up that earns marks\n1. Coupling to **GND** \u2192 a flat line at true zero.\n2. **Vertical Position** \u2192 park that line on the centre graticule line.\n3. Back to **DC** \u2192 now measure amplitudes and DC offsets from a known reference.\n\n### Exam traps\n- **AC coupling hides the DC offset** \u2014 switch to DC before measuring one.\n- The CRO never alters the signal; it only displays it."
    },
    {
      "id": "cro-calculations",
      "name": "CRO Waveform Calculations",
      "summaryNotes": "### The five formulas\n$$V_{p\\text{-}p} = (\\text{vert. div}) \\times (\\text{Volts/Div})$$\n$$V_p = \\frac{V_{p\\text{-}p}}{2},\\qquad V_{rms} = 0.707\\,V_p,\\;\\; V_p = 1.414\\,V_{rms}$$\n$$T = (\\text{horiz. div per cycle}) \\times (\\text{Time/Div}),\\qquad f = \\frac{1}{T}$$\n$$\\phi = \\frac{\\text{shift div}}{\\text{div per cycle}} \\times 360^\\circ$$\n$$\\frac{f_y}{f_x} = \\frac{\\text{horizontal tangencies}}{\\text{vertical tangencies}}$$\n\n### DC-offset signals\n$$V_{DC} = \\frac{(\\text{top div}) + (\\text{bottom div})}{2} \\times (\\text{Volts/Div})$$\nThe offset is the **midpoint** of the waveform, not its peak.\n\n### Exam traps\n- **milli** = $10^{-3}$: convert to seconds **before** computing frequency.\n- RMS is **0.707 \u00d7 peak**, never 0.707 \u00d7 peak-to-peak.\n- Phase needs no Time/Div \u2014 the units cancel because both measurements are in divisions.\n- Lissajous figures only read cleanly when the frequencies are in a **simple integer ratio**."
    }
  ]
}

export const questionBank = {
  "eee282": [
    {
      "id": "eee282_q01",
      "topicId": "active-passive",
      "kind": "theory",
      "type": "mcq",
      "question": "Which fundamental property strictly distinguishes an active component from a passive component in an electrical circuit?",
      "options": [
        "Active components dissipate energy, whereas passive components generate energy.",
        "Active components require an external power source to control electrical current or provide power gain.",
        "Passive components have non-linear voltage-current (V-I) characteristics.",
        "Passive components can amplify electrical signals without external power."
      ],
      "correct": 1,
      "short": "Active parts need an external supply and can control current or deliver power gain; passive parts cannot add net energy to a circuit.",
      "solution": "### The distinction\nAn **active** component needs an external power source to do its job and can use that supply to\n*control* current or deliver **power gain** (amplification). A **passive** component cannot\nintroduce net energy: it only stores, dissipates or releases what is fed into it.\n\n### Quick test\n- Can it amplify, switch or rectify with the help of a supply rail? \u2192 **active**\n  (transistor, diode, SCR, op-amp, MOSFET, LED, zener).\n- Does it merely resist, store or transfer energy with no gain? \u2192 **passive**\n  (resistor, capacitor, inductor, potentiometer, LDR, thermistor, transformer).\n\n### Why the others are wrong\n- *\"Active dissipates, passive generates\"* \u2014 exactly backwards. Dissipation is the passive\n  signature (a resistor turns energy into heat); generation needs an active device plus a supply.\n- *\"Passive has non-linear V-I\"* \u2014 non-linearity is **not** the test. A diode is non-linear and\n  active; a thermistor is non-linear and passive.\n- *\"Passive can amplify without external power\"* \u2014 amplification needs an energy source. Without\n  one, the output power can never exceed the input power."
    },
    {
      "id": "eee282_q02",
      "topicId": "active-passive",
      "kind": "theory",
      "type": "mcq",
      "image": "/images/eee282/q02.svg",
      "question": "A standard PN junction diode is classified as an active component primarily because:",
      "options": [
        "It stores electrical energy in a magnetic field.",
        "It possesses a non-linear V-I characteristic and controls current flow based on bias direction.",
        "It increases the total output power of an AC signal.",
        "It functions as a linear variable resistor."
      ],
      "correct": 1,
      "short": "The diode is a semiconductor whose conduction depends on bias direction \u2014 it controls current rather than merely resisting it.",
      "solution": "### Why the diode is active\nA PN junction is a **semiconductor** device. Its behaviour depends on the *direction* of the applied\nvoltage: forward bias \u2192 conduction after about $0.7\\,\\text{V}$ (silicon); reverse bias \u2192 blocking.\nThat directional control of current is an active property.\n\n### Reading the symbol (see figure)\n- **Anode (A)** \u2014 P-type side, the plain triangle; connect to the **positive** rail for conduction.\n- **Cathode (K)** \u2014 N-type side, the bar; the **band** printed on the body marks this end.\n- Conventional current flows **anode \u2192 cathode**, i.e. in the direction the triangle points.\n\n### Why the others are wrong\n- *Stores energy in a magnetic field* \u2192 that is an **inductor** (passive).\n- *Increases the output power of an AC signal* \u2192 a diode cannot amplify; it rectifies, and in fact\n  it *loses* power across its junction drop.\n- *Linear variable resistor* \u2192 a diode is deliberately **non-linear**; a potentiometer is the linear\n  variable resistor."
    },
    {
      "id": "eee282_q03",
      "topicId": "active-passive",
      "kind": "theory",
      "type": "text",
      "image": "/images/eee282/q03.svg",
      "question": "When connecting a 3-terminal potentiometer as a variable voltage divider, across which two terminals is the input supply voltage connected, and from which terminal is the variable output tapped?",
      "options": [
        "Input supply across terminals 1 and 3 (the two ends of the resistive track); output taken from terminal 2 (the wiper).",
        "Input supply across terminals 1 and 2; output taken from terminal 3.",
        "Input supply across terminals 2 and 3; output taken from terminal 1.",
        "Input supply to the wiper (terminal 2) and terminal 1; output taken from terminal 3."
      ],
      "correct": 0,
      "expected": "Supply across the outer terminals 1 and 3; output tapped from the wiper, terminal 2.",
      "match": {
        "all": [
          "wiper",
          "1",
          "3"
        ],
        "any": [
          "2"
        ]
      },
      "short": "The full track sits between pins 1 and 3, so the supply goes there; the wiper (pin 2) is the slider that taps off any fraction of it.",
      "solution": "### Potentiometer as a voltage divider\nA potentiometer is one resistive track with a moving contact:\n\n- **Terminals 1 and 3** \u2014 the two fixed ends of the track. The **whole** resistance $R$ lies\n  between them, so the **supply is connected across 1 and 3**.\n- **Terminal 2** \u2014 the **wiper** (slider). Its position sets the ratio, so the **output is taken\n  from terminal 2** (usually with the other side of the output on terminal 1 or 3).\n\n### The working equation\n$$V_{out} = V_{in}\\times\\frac{R_{2\\to3}}{R_{1\\to3}}$$\nAt the bottom of the travel $V_{out}=0$; at the top $V_{out}=V_{in}$; everywhere between it varies\nsmoothly \u2014 which is exactly what \"variable voltage divider\" means.\n\n### Exam traps\n- Wiring the supply to the wiper and one end turns it into a **rheostat** (variable resistor), not\n  a divider \u2014 you lose the ability to swing the output through the full range.\n- Always confirm the pin numbering from the datasheet: on some trimmers the wiper is the middle\n  pin, on others it is not."
    },
    {
      "id": "eee282_q04",
      "topicId": "active-passive",
      "kind": "theory",
      "type": "mcq",
      "image": "/images/eee282/q04.svg",
      "question": "How does the resistance of a Negative Temperature Coefficient (NTC) Thermistor behave as ambient temperature increases?",
      "options": [
        "Resistance increases linearly.",
        "Resistance remains constant.",
        "Resistance decreases.",
        "Resistance drops abruptly to exactly zero."
      ],
      "correct": 2,
      "short": "NTC = Negative Temperature Coefficient: heat frees more charge carriers, so resistance falls as temperature rises.",
      "solution": "### NTC behaviour\nHeat gives bound electrons in the semiconductor enough energy to become **free charge carriers**.\nMore carriers means **lower resistance**, so an NTC thermistor's resistance *falls* as temperature\n*rises* \u2014 the \"N\" in NTC.\n\n### Remember it this way\n- **NTC** \u2192 **N**egative coefficient \u2192 temperature up, resistance **down**. Used for temperature\n  sensing, inrush-current limiting, and thermostat inputs.\n- **PTC** \u2192 **P**ositive coefficient \u2192 temperature up, resistance **up**. Used as a self-resetting\n  fuse and for over-current protection.\n\n### Why the others are wrong\n- *Increases linearly* \u2014 that describes a PTC, and even then the curve is not perfectly linear.\n- *Remains constant* \u2014 that is an ideal fixed resistor, not a thermistor.\n- *Drops to exactly zero* \u2014 resistance falls steeply but never reaches zero; only a superconductor\n  (not a thermistor) does that."
    },
    {
      "id": "eee282_q05",
      "topicId": "active-passive",
      "kind": "theory",
      "type": "mcq",
      "image": "/images/eee282/q05.svg",
      "question": "A Light Dependent Resistor (LDR) exhibits its highest resistance under which ambient condition?",
      "options": [
        "Direct sunlight",
        "Total darkness",
        "High temperature",
        "High AC frequency input"
      ],
      "correct": 1,
      "short": "Light creates carriers and lowers resistance, so the LDR is at its maximum resistance in total darkness.",
      "solution": "### LDR behaviour\nPhotons striking the semiconductor free charge carriers. More light \u2192 more carriers \u2192 **lower\nresistance**. In **total darkness** almost no carriers are freed, so the resistance is at its\nmaximum (typically hundreds of k\u03a9 to M\u03a9, versus a few k\u03a9 in bright light).\n\n### Typical values to quote in the lab\n- Dark: $R$ in the **M\u03a9** range.\n- Bright light / direct sun: $R$ falls to **hundreds of \u03a9 to a few k\u03a9**.\n\n### Why the others are wrong\n- *Direct sunlight* \u2014 that is where the resistance is **lowest**, not highest.\n- *High temperature* \u2014 temperature is the thermistor's input variable, not the LDR's.\n- *High AC frequency* \u2014 an LDR responds to light intensity, not to signal frequency."
    },
    {
      "id": "eee282_q06",
      "topicId": "active-passive",
      "kind": "theory",
      "type": "mcq",
      "image": "/images/eee282/q06.svg",
      "question": "Which capacitor type is polarized and requires strict terminal orientation during circuit assembly?",
      "options": [
        "Ceramic Capacitor",
        "Mica Capacitor",
        "Electrolytic Capacitor",
        "Film Capacitor"
      ],
      "correct": 2,
      "short": "Electrolytic capacitors are polarised \u2014 the oxide dielectric is formed electrochemically, so the positive lead must go to the positive rail.",
      "solution": "### Polarised vs non-polarised\nAn **electrolytic** capacitor builds its dielectric as a microscopic **oxide layer** by\nelectrochemical action. Reverse that chemistry and the oxide breaks down: the part heats, vents and\ncan fail violently.\n\n### Identification in the lab\n- **Electrolytic** \u2014 long lead is **positive**, a printed **stripe with a minus sign** marks the\n  negative side; values from about $1\\,\\mu\\text{F}$ upward, always polarised.\n- **Ceramic / mica / film** \u2014 no polarity marking; safe to fit either way; usually pF to low \u00b5F.\n\n### Exam trap\nFitting an electrolytic backwards is the single most common practical fault in a first-year power\nsupply. If a question mentions a smoothing capacitor on a rectifier, check the polarity first.\n\n### Why the others are wrong\nCeramic, mica and film capacitors use a solid dielectric with no electrochemistry, so they are\nnon-polarised and orientation does not matter."
    },
    {
      "id": "eee282_q07",
      "topicId": "active-passive",
      "kind": "theory",
      "type": "mcq",
      "image": "/images/eee282/q07.svg",
      "question": "A Zener diode is specifically designed to operate safely in which region?",
      "options": [
        "Forward saturation region",
        "Cut-off region",
        "Reverse breakdown region",
        "Ohmic linear region"
      ],
      "correct": 2,
      "short": "A zener is doped to break down at a precise reverse voltage without damage \u2014 that constant voltage is what makes it a regulator.",
      "solution": "### Zener operation\nAn ordinary diode is destroyed by reverse breakdown. A **zener** is doped so that breakdown occurs\nat a precise, repeatable voltage ($V_Z$) and the device survives it. In that region the voltage\nacross it stays almost constant while the current changes \u2014 the basis of a **shunt regulator**.\n\n### Series resistor is mandatory\nA zener must **never** be connected straight across a supply. The series resistor $R_S$ limits the\ncurrent:\n$$R_S = \\frac{V_{in}-V_Z}{I_Z}$$\nWithout it the zener exceeds its power rating and burns out.\n\n### Why the others are wrong\n- *Forward saturation / cut-off / ohmic linear* \u2014 these describe normal diode conduction or\n  blocking. The zener's whole purpose is controlled **reverse breakdown**, which is why its symbol\n  has the distinctive **Z-shaped cathode**."
    },
    {
      "id": "eee282_q08",
      "topicId": "active-passive",
      "kind": "theory",
      "type": "text",
      "question": "Classify the following four components as either ACTIVE or PASSIVE: MOSFET, Potentiometer, Op-Amp, Inductor.",
      "options": [
        "MOSFET: Active, Potentiometer: Passive, Op-Amp: Active, Inductor: Passive",
        "MOSFET: Passive, Potentiometer: Active, Op-Amp: Passive, Inductor: Active",
        "All four are active devices.",
        "All four are passive devices."
      ],
      "correct": 0,
      "expected": "MOSFET: Active \u00b7 Potentiometer: Passive \u00b7 Op-Amp: Active \u00b7 Inductor: Passive",
      "match": {
        "all": [
          "active",
          "passive"
        ],
        "minAny": {
          "n": 3,
          "list": [
            "mosfet",
            "potentiometer",
            "op-amp",
            "op amp",
            "opamp",
            "inductor"
          ]
        }
      },
      "short": "MOSFET and op-amp are active (both need a supply and give gain/control); potentiometer and inductor are passive.",
      "solution": "### Classification\n| Component | Class | Why |\n|---|---|---|\n| **MOSFET** | Active | Needs a supply; a gate voltage controls a much larger drain current \u2192 gain. |\n| **Potentiometer** | Passive | A resistive divider. It *attenuates*; it can never add energy. |\n| **Op-Amp** | Active | Needs supply rails and delivers very large voltage gain. |\n| **Inductor** | Passive | Stores energy in a magnetic field and gives it back; no gain. |\n\n### The one-line rule\nAsk: *\"Can this part use a power supply to control a bigger signal, or amplify?\"* Yes \u2192 active.\nNo \u2192 passive.\n\n### Why the other options are wrong\n- Calling the MOSFET or op-amp passive ignores the supply pin and the gain they provide.\n- Calling the potentiometer or inductor active confuses *control* (a knob) with *gain* \u2014 turning a\n  knob does not inject energy into the circuit."
    },
    {
      "id": "eee282_q09",
      "topicId": "bjt-diagnostics",
      "kind": "theory",
      "type": "mcq",
      "question": "When using a digital multimeter in Diode mode to identify a BJT's Base terminal, what specific reading pattern confirms you have found the Base?",
      "options": [
        "A single pin that shows 'OL' to both other pins.",
        "A single pin that shows a forward voltage drop (approximately 0.6 V - 0.7 V) to BOTH of the other pins.",
        "A single pin that shows 0.000 V to one pin and 'OL' to the other.",
        "A pin that shows equal resistance in both directions."
      ],
      "correct": 1,
      "short": "A BJT behaves like two diodes sharing one terminal. The base is the only pin that conducts (\u22480.6\u20130.7 V) to both other pins with one probe polarity.",
      "solution": "### The two-diodes model\nA BJT is two PN junctions back-to-back sharing one terminal \u2014 the **base**:\n\n- **NPN:** two diodes with their **anodes** tied together at the base.\n- **PNP:** two diodes with their **cathodes** tied together at the base.\n\nSo with the correct probe polarity, **one pin** (the base) will show a junction drop of about\n**0.6\u20130.7 V to each of the other two pins**.\n\n### Procedure\n1. Put the red probe on a candidate pin; touch black to the other two in turn.\n2. If **both** read \u22480.6\u20130.7 V, the red probe is on the base of an **NPN**.\n3. If both read `OL`, swap: black on that pin, red to the others. Two drops \u2192 **PNP**, base found.\n4. Try the remaining pins until one gives the pattern.\n\n### Why the others are wrong\n- *OL to both pins* \u2014 that is the signature of the **collector-emitter** path on a healthy\n  transistor, not the base.\n- *0.000 V to one pin* \u2014 a dead short, which means a **faulty** device.\n- *Equal resistance both ways* \u2014 that is a plain resistor, not a junction."
    },
    {
      "id": "eee282_q10",
      "topicId": "bjt-diagnostics",
      "kind": "theory",
      "type": "mcq",
      "question": "If placing the RED (positive) multimeter probe on Pin 2 yields a ~0.65 V drop to Pin 1 and a ~0.65 V drop to Pin 3, what is the polarity type of this transistor?",
      "options": [
        "PNP",
        "NPN",
        "JFET",
        "MOSFET"
      ],
      "correct": 1,
      "short": "Red probe common = NPN. The red lead supplies positive bias, so the shared pin must be P-type material between two N regions.",
      "solution": "### Reasoning\nA meter in diode mode pushes current out of its **red** lead. If red sits on one pin and both other\npins show a forward drop, red must be on the **anodes** of both junctions \u2014 i.e. the **P-type**\nmiddle layer. P between two N layers is **NPN**.\n\n### Memory aid\n- **Red common \u2192 NPN** (\"Red = N ot Pointing iN\", or simply red = positive = anode = P-material).\n- **Black common \u2192 PNP.** (Black is the negative/com lead; it sits on the N-type middle layer.)\n\n### Why the others are wrong\n- *PNP* would need the **black** probe on the common pin to show the two drops.\n- *JFET / MOSFET* are not identified this way \u2014 a FET has no gate junction drop, and its\n  drain-source path behaves like a resistor or a protected diode, not two junction drops."
    },
    {
      "id": "eee282_q11",
      "topicId": "bjt-diagnostics",
      "kind": "theory",
      "type": "mcq",
      "question": "If placing the BLACK (negative) multimeter probe on Pin 1 yields a ~0.68 V drop to Pin 2 and a ~0.68 V drop to Pin 3, what is the polarity type of this transistor?",
      "options": [
        "PNP",
        "NPN",
        "Zener",
        "SCR"
      ],
      "correct": 0,
      "short": "Black probe common = PNP. Black is the negative lead, so the shared pin is the N-type middle layer between two P regions.",
      "solution": "### Reasoning\nWith **black** (COM, negative) on one pin and a forward drop to both others, current is flowing\n*out of* the other two pins *into* the black lead. That means the shared pin is the **cathodes**\nside \u2014 the **N-type** middle layer. N between two P layers is **PNP**.\n\n### Pair it with q10\n| Common probe | Reading | Device |\n|---|---|---|\n| Red on the pin | \u22480.6 V to both other pins | **NPN** |\n| Black on the pin | \u22480.6 V to both other pins | **PNP** |\n\n### Why the others are wrong\n- *NPN* requires the **red** probe on the common pin.\n- *Zener / SCR* \u2014 a zener is a two-terminal device; an SCR has a gate but its anode-cathode path\n  reads `OL` both ways, so neither produces this three-pin two-drop pattern."
    },
    {
      "id": "eee282_q12",
      "topicId": "bjt-diagnostics",
      "kind": "theory",
      "type": "mcq",
      "question": "Once the Base terminal is identified, how do you distinguish the Emitter pin from the Collector pin using the multimeter's voltage drop readings?",
      "options": [
        "The Base-Collector junction always has a higher voltage drop than the Base-Emitter junction.",
        "The Base-Emitter junction always has a slightly higher voltage drop than the Base-Collector junction.",
        "The Emitter pin will show an 'OL' reading.",
        "The Collector pin will beep in continuity mode."
      ],
      "correct": 1,
      "short": "The emitter is more heavily doped than the collector, so V_BE reads a few millivolts higher than V_BC \u2014 the higher drop is the emitter.",
      "solution": "### The doping rule\nIn a BJT the **emitter is heavily doped** and the **collector is lightly doped** (so it can sustain\na large reverse voltage). Heavier doping gives a **slightly larger junction drop**, so:\n\n$$V_{BE} > V_{BC}\\quad\\text{(by roughly 5\u201315 mV)}$$\n\n### Worked example\nBase found with red on pin 2; black to pin 1 reads **0.712 V**, black to pin 3 reads **0.704 V**.\nThe **larger** reading, 0.712 V, is the **emitter** \u2192 pin 1. Pin 3 is the collector.\n\n### Why the others are wrong\n- *Base-Collector higher* \u2014 the reverse of the physics; the collector is the lightly doped side.\n- *Emitter reads OL* \u2014 an `OL` reading means an open circuit, which would be a **faulty** device.\n- *Collector beeps in continuity* \u2014 a healthy collector-emitter path does not conduct at all.\n\n### Exam tip\nThe difference is small, so **write both readings down to the millivolt** before deciding. If the\ntwo drops are identical to the last digit, re-measure \u2014 one of them will be higher."
    },
    {
      "id": "eee282_q13",
      "topicId": "bjt-diagnostics",
      "kind": "theory",
      "type": "text",
      "image": "/images/eee282/q13.svg",
      "question": "You are testing an unknown transistor. With the RED probe on Pin 3, you measure 0.712 V on Pin 1 and 0.704 V on Pin 2. Identify the Type (NPN/PNP), Base, Emitter and Collector pins.",
      "options": [
        "NPN \u2014 Base = Pin 3, Emitter = Pin 1, Collector = Pin 2",
        "NPN \u2014 Base = Pin 3, Emitter = Pin 2, Collector = Pin 1",
        "PNP \u2014 Base = Pin 3, Emitter = Pin 1, Collector = Pin 2",
        "NPN \u2014 Base = Pin 1, Emitter = Pin 3, Collector = Pin 2"
      ],
      "correct": 0,
      "expected": "Type: NPN \u00b7 Base = Pin 3 \u00b7 Emitter = Pin 1 (0.712 V) \u00b7 Collector = Pin 2 (0.704 V)",
      "match": {
        "all": [
          "npn",
          "1",
          "2",
          "3"
        ]
      },
      "short": "Red common \u2192 NPN, so pin 3 is the base. The higher drop (0.712 V on pin 1) is the emitter; 0.704 V on pin 2 is the collector.",
      "solution": "### Step 1 \u2014 Find the base and the type\nThe **red** probe is fixed on **pin 3** and *both* other pins show a junction drop, so pin 3 is the\ncommon pin \u2192 **base**, and **red common means NPN**.\n\n### Step 2 \u2014 Split emitter from collector\nCompare the two readings:\n\n- Pin 1 \u2192 **0.712 V** (larger)\n- Pin 2 \u2192 **0.704 V** (smaller)\n\nThe emitter is more heavily doped, so $V_{BE} > V_{BC}$.\n**Larger drop = emitter \u2192 pin 1.** Therefore **pin 2 is the collector**.\n\n### Answer\n| Quantity | Value |\n|---|---|\n| Type | **NPN** |\n| Base | **Pin 3** |\n| Emitter | **Pin 1** (0.712 V) |\n| Collector | **Pin 2** (0.704 V) |\n\n### Why the other options are wrong\n- Swapping emitter/collector ignores the doping rule (the 8 mV difference is the whole clue).\n- Calling it PNP contradicts \"red probe common\".\n- Making pin 1 the base contradicts the statement that the *fixed* probe was on pin 3."
    },
    {
      "id": "eee282_q14",
      "topicId": "bjt-diagnostics",
      "kind": "theory",
      "type": "text",
      "question": "You are testing a transistor. With the BLACK probe on Pin 2, you measure 0.655 V on Pin 1 and 0.661 V on Pin 3. Identify the Type (NPN/PNP), Base, Emitter and Collector pins.",
      "options": [
        "PNP \u2014 Base = Pin 2, Emitter = Pin 3, Collector = Pin 1",
        "PNP \u2014 Base = Pin 2, Emitter = Pin 1, Collector = Pin 3",
        "NPN \u2014 Base = Pin 2, Emitter = Pin 3, Collector = Pin 1",
        "PNP \u2014 Base = Pin 1, Emitter = Pin 3, Collector = Pin 2"
      ],
      "correct": 0,
      "expected": "Type: PNP \u00b7 Base = Pin 2 \u00b7 Emitter = Pin 3 (0.661 V) \u00b7 Collector = Pin 1 (0.655 V)",
      "match": {
        "all": [
          "pnp",
          "1",
          "2",
          "3"
        ]
      },
      "short": "Black common \u2192 PNP, so pin 2 is the base. The higher drop (0.661 V on pin 3) is the emitter; 0.655 V on pin 1 is the collector.",
      "solution": "### Step 1 \u2014 Find the base and the type\nThe **black** probe is fixed on **pin 2** and both other pins show a drop \u2192 pin 2 is the **base**,\nand **black common means PNP**.\n\n### Step 2 \u2014 Split emitter from collector\n- Pin 1 \u2192 0.655 V\n- Pin 3 \u2192 **0.661 V** (larger)\n\nLarger drop = **emitter** \u2192 **pin 3**. So **pin 1 is the collector**.\n\n### Answer\n| Quantity | Value |\n|---|---|\n| Type | **PNP** |\n| Base | **Pin 2** |\n| Emitter | **Pin 3** (0.661 V) |\n| Collector | **Pin 1** (0.655 V) |\n\n### Exam tip\nThe gap here is only **6 mV**. Decide nothing from memory of \"pin order\" \u2014 always let the larger\nnumber name the emitter. This is the classic question where students lose a mark by assuming the\nemitter is always a particular physical pin."
    },
    {
      "id": "eee282_q15",
      "topicId": "bjt-diagnostics",
      "kind": "theory",
      "type": "mcq",
      "question": "When testing a healthy BJT in Diode mode, what reading should you get if you place your probes directly across the Collector and Emitter pins?",
      "options": [
        "Approximately 0.6 V in one direction, OL in the other.",
        "'OL' (Open Loop) in both directions.",
        "0.000 V in both directions.",
        "The sum of the two base junction voltage drops (approximately 1.2 V)."
      ],
      "correct": 1,
      "short": "Collector-emitter is two junctions back-to-back, so one is always reverse-biased: a healthy BJT reads OL both ways across C-E.",
      "solution": "### Why OL both ways\nBetween collector and emitter the current would have to cross **two junctions in series**, and\nwhichever polarity you choose, **one of them is reverse-biased**. No current flows, so the meter\nshows `OL` in **both** directions.\n\n### This is your health check\n- C-E reads **OL both ways** \u2192 junctions are intact (keep going; identify the pins).\n- C-E reads **0.000 V** \u2192 **shorted** C-E: the device is faulty.\n- Everything reads **OL** \u2192 **open** junctions: the device is blown.\n\n### Why the others are wrong\n- *0.6 V one way, OL the other* \u2014 that is a **single** junction (base-emitter or base-collector),\n  not the C-E path.\n- *0.000 V* \u2014 a short circuit, i.e. a failed transistor.\n- *\u22481.2 V* \u2014 you cannot add the two drops in series because one junction is always reverse-biased."
    },
    {
      "id": "eee282_q16",
      "topicId": "bjt-diagnostics",
      "kind": "theory",
      "type": "text",
      "question": "You test a transistor and find the Base is Pin 1 (NPN). However, when you measure between Pin 2 and Pin 3, the multimeter reads 0.000 V. What is the condition of this transistor?",
      "options": [
        "The transistor is faulty \u2014 the collector and emitter are short-circuited.",
        "The transistor is healthy and is an NPN.",
        "The transistor is healthy and is a PNP.",
        "The transistor is faulty \u2014 the base junction is open circuit."
      ],
      "correct": 0,
      "expected": "Faulty \u2014 collector-emitter short circuit (C-E should read OL on a healthy BJT).",
      "match": {
        "any": [
          "faulty",
          "short",
          "shorted",
          "blown",
          "damaged",
          "dead",
          "open"
        ]
      },
      "short": "A healthy C-E path must read OL. 0.000 V means the silicon has failed into a short, so the transistor is dead.",
      "solution": "### Diagnosis\nOn a healthy BJT the collector-emitter path reads **`OL` in both directions** (two opposing\njunctions). A reading of **0.000 V** means the meter sees a **dead short** \u2014 the semiconductor\nmaterial between those pins has broken down and fused.\n\n### Verdict\n**The transistor is faulty \u2014 short-circuited collector to emitter.** Bin it; do not build with it.\n\n### Fault table for revision\n| Measurement | Meaning |\n|---|---|\n| C-E reads `OL` both ways | Healthy \u2014 expected result |\n| C-E reads `0.000 V` | **Shorted** C-E \u2192 faulty |\n| No junction drop anywhere | **Open** junctions \u2192 faulty (blown) |\n| Junction drop on base + C-E short | Partly shorted \u2192 faulty |\n\n### Why the other options are wrong\n- \"Healthy\" is impossible with a C-E short: the device can no longer block voltage.\n- An **open** base junction would read `OL`, not `0.000 V`."
    },
    {
      "id": "eee282_q17",
      "topicId": "bjt-diagnostics",
      "kind": "theory",
      "type": "mcq",
      "question": "If every possible probe combination on a 3-pin BJT yields an 'OL' reading on your multimeter, what does this indicate?",
      "options": [
        "It is a healthy NPN transistor.",
        "The multimeter is in the wrong mode; it must be in Ohms.",
        "The transistor is faulty (internally open/blown).",
        "It is a healthy PNP transistor."
      ],
      "correct": 2,
      "short": "No forward drop on any of the six probe combinations means both junctions are open \u2014 the transistor is blown.",
      "solution": "### Reasoning\nA good BJT must show **two** forward drops (base\u2192emitter and base\u2192collector). If all **six** probe\ncombinations read `OL`, **neither junction conducts**: both are open circuit. The device is\n**faulty (internally open / blown)**.\n\n### Before you condemn it \u2014 check yourself\n1. Meter is in **diode mode**, leads in the **V\u03a9 / diode** jacks (not the 10 A jack).\n2. The transistor is **out of circuit**; in-circuit readings are unreliable.\n3. Leads are actually touching the pins (oxidation or a breadboard can fool you).\n4. Compare against a known-good transistor to confirm the meter works.\n\n### Why the others are wrong\n- A healthy NPN or PNP **must** show two junction drops \u2014 `OL` everywhere is impossible.\n- Ohms mode usually cannot forward-bias a silicon junction (its test voltage is too low), so the\n  Ohms suggestion would make the problem worse, not fix it."
    },
    {
      "id": "eee282_q18",
      "topicId": "bjt-diagnostics",
      "kind": "theory",
      "type": "mcq",
      "question": "You are probing a component with Red on Pin 1. Pin 2 shows 0.6 V and Pin 3 shows 'OL'. Switching to Black on Pin 1, Pin 2 shows 'OL' and Pin 3 shows 0.6 V. Is this a BJT?",
      "options": [
        "Yes, it is an NPN.",
        "Yes, it is a PNP.",
        "No, a BJT must have a single common pin that conducts to both other pins with the same polarity.",
        "Yes, but the Base is broken."
      ],
      "correct": 2,
      "short": "No \u2014 a BJT needs one pin that reads a drop to BOTH other pins with the SAME probe polarity. This pattern is two back-to-back diodes or two discrete diodes.",
      "solution": "### The BJT signature\nA BJT is two diodes sharing a node, so there **must** exist one pin and one probe polarity that\nforward-biases **both** junctions at once. Here:\n\n- Red on pin 1 \u2192 pin 2 conducts (0.6 V), pin 3 does **not** (`OL`).\n- Black on pin 1 \u2192 pin 3 conducts (0.6 V), pin 2 does **not** (`OL`).\n\nNo single polarity on pin 1 reaches both pins, and repeating the test on pins 2 and 3 gives the\nsame \"one conducts, one doesn't\" pattern. **No common pin \u2192 not a BJT.**\n\n### What it could be\nTwo **discrete diodes wired back-to-back** (or a diode network / a triac-like structure). Each\njunction works on its own, but they do not share a base.\n\n### Why the other options are wrong\n- *NPN / PNP* \u2014 both require a pin that shows a drop to the other two **simultaneously**.\n- *\"Base is broken\"* \u2014 if the base were open you would read `OL` on **every** combination, not\n  0.6 V on four of them."
    },
    {
      "id": "eee282_q19",
      "topicId": "cro-controls",
      "kind": "theory",
      "type": "mcq",
      "question": "Which control knob on a Cathode Ray Oscilloscope (CRO) adjusts the horizontal scale of the displayed waveform?",
      "options": [
        "Volts/Div",
        "Focus Control",
        "Time/Div (Time Base)",
        "Vertical Position"
      ],
      "correct": 2,
      "short": "Time/Div (the time base) sets how much time each horizontal division represents \u2014 the horizontal scale.",
      "solution": "### The two axes\n- **Horizontal axis = time** \u2192 controlled by **Time/Div** (the time base, in s/div, ms/div or \u00b5s/div).\n- **Vertical axis = voltage** \u2192 controlled by **Volts/Div**.\n\n### Using it\n$$T = (\\text{divisions per cycle}) \\times (\\text{Time/Div setting}),\\qquad f = \\frac{1}{T}$$\nIncrease Time/Div and the trace spreads out horizontally, showing fewer cycles; decrease it and you\nsee more cycles in less detail.\n\n### Why the others are wrong\n- *Volts/Div* \u2014 the vertical (amplitude) scale.\n- *Focus* \u2014 sharpness of the spot; it changes clarity, not scale.\n- *Vertical Position* \u2014 moves the trace up and down; it does not rescale anything."
    },
    {
      "id": "eee282_q20",
      "topicId": "cro-controls",
      "kind": "theory",
      "type": "mcq",
      "question": "The primary function of the Volts/Div knob on a CRO is to:",
      "options": [
        "Alter the frequency of the input signal.",
        "Set the vertical amplitude scale (voltage represented per division).",
        "Adjust the electron beam sharpness.",
        "Shift the wave horizontally along the time axis."
      ],
      "correct": 1,
      "short": "Volts/Div sets the vertical sensitivity: how many volts each vertical division represents.",
      "solution": "### Volts/Div = vertical sensitivity\nIt scales the vertical deflection, fixing how many **volts** one vertical division represents\n(e.g. 2 V/div, 5 V/div). Everything amplitude-related is read with it:\n$$V_{p\\text{-}p} = (\\text{vertical divisions}) \\times (\\text{Volts/Div})$$\n\n### Practical note\nTurning the knob to a **smaller** V/div magnifies the waveform vertically \u2014 useful for small\nsignals, but it also magnifies noise and can drive the trace off-screen.\n\n### Why the others are wrong\n- *Alter the frequency* \u2014 a CRO never changes the signal; it only displays it.\n- *Beam sharpness* \u2014 that is **Focus** (with **Intensity** for brightness).\n- *Shift the wave horizontally* \u2014 that is **Horizontal Position** (or the trigger level)."
    },
    {
      "id": "eee282_q21",
      "topicId": "cro-controls",
      "kind": "theory",
      "type": "mcq",
      "question": "When the input coupling switch of a CRO channel is set to 'AC Coupling', what happens to the incoming signal?",
      "options": [
        "The AC component is blocked, passing only DC voltage.",
        "A series capacitor blocks any DC offset voltage, passing only the AC signal.",
        "The signal is directly grounded.",
        "The signal amplitude is multiplied by a factor of 10."
      ],
      "correct": 1,
      "short": "AC coupling puts a capacitor in series: it strips the DC level and passes only the varying part of the signal.",
      "solution": "### AC vs DC vs GND\n- **DC coupling** \u2014 the signal is connected straight through. You see **AC + DC** together, so you\n  can measure a DC offset directly (needed for questions like q28).\n- **AC coupling** \u2014 a **series capacitor** blocks the DC component, so the trace centres on zero\n  and shows only the **varying** part. Ideal for inspecting a small ripple sitting on a large DC\n  rail.\n- **GND** \u2014 the input is grounded; the trace shows the **0 V reference**, which is how you position\n  the zero baseline before measuring.\n\n### Why the others are wrong\n- *\"AC is blocked, DC passes\"* \u2014 backwards: the capacitor **blocks DC**.\n- *Signal grounded* \u2014 that is the **GND** coupling position, not AC.\n- *\u00d710* \u2014 amplitude scaling is done by the **Volts/Div** knob or a \u00d710 **probe**, not by coupling."
    },
    {
      "id": "eee282_q22",
      "topicId": "cro-controls",
      "kind": "theory",
      "type": "calc",
      "question": "What is the standard physical dimension of one major box grid (graticule) on a typical CRO screen display?",
      "options": [
        "1 cm \u00d7 1 cm",
        "0.5 cm \u00d7 0.5 cm",
        "2 cm \u00d7 2 cm",
        "1 inch \u00d7 1 inch"
      ],
      "correct": 0,
      "num": {
        "values": [
          1
        ],
        "unit": "cm"
      },
      "expected": "1 cm \u00d7 1 cm (one division)",
      "short": "One major graticule division is 1 cm \u00d7 1 cm on a standard CRO screen.",
      "solution": "### The graticule\nThe screen is etched (or drawn) with a grid of **major divisions**, each **1 cm \u00d7 1 cm**. A typical\ndisplay is **8 vertical \u00d7 10 horizontal** divisions, and the minor ticks subdivide each major\ndivision into **5**.\n\n### Why it matters\nEvery CRO measurement is a count of divisions:\n- Amplitude: $V_{p\\text{-}p} = \\text{vertical divisions} \\times \\text{Volts/Div}$\n- Time: $T = \\text{horizontal divisions} \\times \\text{Time/Div}$\n\n### Why the others are wrong\n- 0.5 cm and 2 cm are not the standard major division; 1 **inch** (2.54 cm) is far too large for\n  an oscilloscope graticule."
    },
    {
      "id": "eee282_q23",
      "topicId": "cro-controls",
      "kind": "theory",
      "type": "mcq",
      "question": "Which control knob is adjusted to shift the entire displayed waveform up or down without altering its peak magnitude?",
      "options": [
        "Horizontal Position Knob",
        "Vertical Position Knob",
        "Intensity Knob",
        "Volts/Div Knob"
      ],
      "correct": 1,
      "short": "The Vertical Position knob adds a DC offset to the deflection, sliding the whole trace up or down without changing its amplitude.",
      "solution": "### Vertical Position\nIt injects a small DC bias into the vertical deflection system, translating the **whole** trace up\nor down. The peak-to-peak amplitude is unchanged \u2014 only where the trace sits on the screen changes.\n\n### Classic use\n1. Set coupling to **GND** \u2014 the trace becomes a flat line at the true **0 V** level.\n2. Use **Vertical Position** to park that line on the centre graticule line.\n3. Switch back to **DC** coupling \u2014 now every amplitude and DC-offset measurement is referenced to\n   a known zero.\n\n### Why the others are wrong\n- *Horizontal Position* \u2014 moves the trace left/right in time.\n- *Intensity* \u2014 brightness of the trace.\n- *Volts/Div* \u2014 this **does** change the displayed magnitude, which the question rules out."
    },
    {
      "id": "eee282_q24",
      "topicId": "cro-calculations",
      "kind": "calc",
      "type": "calc",
      "image": "/images/eee282/q24.svg",
      "question": "A sinusoidal wave covers 4 vertical major divisions from its lowest trough to its highest peak. If the Volts/Div knob is set to 5 V/div, calculate: (i) Peak-to-Peak Voltage (Vp-p), (ii) Peak Voltage (Vp), and (iii) RMS Voltage (Vrms).",
      "options": [
        "Vp-p = 20 V, Vp = 10 V, Vrms = 7.07 V",
        "Vp-p = 20 V, Vp = 10 V, Vrms = 14.14 V",
        "Vp-p = 10 V, Vp = 20 V, Vrms = 7.07 V",
        "Vp-p = 20 V, Vp = 5 V, Vrms = 3.54 V"
      ],
      "correct": 0,
      "num": {
        "values": [
          20,
          10,
          7.07
        ],
        "unit": "V"
      },
      "expected": "Vp-p = 20 V, Vp = 10 V, Vrms = 7.07 V",
      "short": "Vp-p = 4 div \u00d7 5 V/div = 20 V; Vp = 10 V; Vrms = 0.707 \u00d7 10 = 7.07 V.",
      "solution": "### Step 1 \u2014 Peak-to-peak from the screen\nThe trough-to-peak height is 4 divisions, and each division is 5 V:\n$$V_{p\\text{-}p} = 4\\ \\text{div} \\times 5\\ \\frac{\\text{V}}{\\text{div}} = 20\\ \\text{V}$$\n\n### Step 2 \u2014 Peak value\n$$V_p = \\frac{V_{p\\text{-}p}}{2} = \\frac{20}{2} = 10\\ \\text{V}$$\n\n### Step 3 \u2014 RMS\nFor a sine wave:\n$$V_{rms} = 0.707\\,V_p = 0.707 \\times 10 = 7.07\\ \\text{V}$$\n\n### Answer\n**Vp-p = 20 V, Vp = 10 V, Vrms = 7.07 V**\n\n### Distractor analysis\n- **14.14 V** \u2014 that is $V_{rms}$ if you (wrongly) start from $V_{p\\text{-}p}=20$ and use\n  $V_{rms}=V_{p\\text{-}p}\\times0.707$. Never: RMS is **0.707 \u00d7 peak**, not 0.707 \u00d7 peak-to-peak.\n- **Vp-p = 10, Vp = 20** \u2014 the halves are swapped; peak can never exceed peak-to-peak.\n- **Vp = 5 V** \u2014 that halves the peak-to-peak **twice** (or mistakes 4 div for 2 div).\n\n### Exam tip\nAlways write the units next to the division count *before* you multiply; most lost marks on CRO\nquestions are unit slips, not arithmetic slips."
    },
    {
      "id": "eee282_q25",
      "topicId": "cro-calculations",
      "kind": "calc",
      "type": "calc",
      "image": "/images/eee282/q25.svg",
      "question": "One complete cycle of a periodic signal spans 5 horizontal divisions on a CRO screen. The Time/Div knob is set to 2 ms/div. Calculate: (i) Period of the signal (T in seconds), and (ii) Frequency of the signal (f in Hz).",
      "options": [
        "T = 0.01 s (10 ms), f = 100 Hz",
        "T = 0.01 s (10 ms), f = 10 Hz",
        "T = 0.1 s (100 ms), f = 10 Hz",
        "T = 10 s, f = 0.1 Hz"
      ],
      "correct": 0,
      "num": {
        "values": [
          0.01,
          100
        ],
        "unit": "s and Hz"
      },
      "expected": "T = 0.01 s (10 ms), f = 100 Hz",
      "short": "T = 5 div \u00d7 2 ms/div = 10 ms = 0.01 s; f = 1/T = 1/0.01 = 100 Hz.",
      "solution": "### Step 1 \u2014 Period from the screen\nOne cycle occupies 5 divisions at 2 ms per division:\n$$T = 5\\ \\text{div} \\times 2\\ \\frac{\\text{ms}}{\\text{div}} = 10\\ \\text{ms} = 0.01\\ \\text{s}$$\n\n### Step 2 \u2014 Frequency\n$$f = \\frac{1}{T} = \\frac{1}{0.01\\ \\text{s}} = 100\\ \\text{Hz}$$\n\n### Answer\n**T = 0.01 s (10 ms), f = 100 Hz**\n\n### Distractor analysis\n- **f = 10 Hz** \u2014 comes from treating 10 ms as 0.1 s. Check the prefix: **milli** = $10^{-3}$, so\n  10 ms = 0.010 s.\n- **T = 0.1 s** \u2014 a factor-of-ten slip on the same prefix conversion.\n- **T = 10 s** \u2014 forgetting to convert ms to s entirely.\n\n### Exam tip\nConvert to **base units before** you divide: $T$ in seconds \u2192 $f$ in hertz, no surprises."
    },
    {
      "id": "eee282_q26",
      "topicId": "cro-calculations",
      "kind": "calc",
      "type": "calc",
      "question": "A sine wave signal has a frequency of 250 Hz. If the Time/Div knob on the CRO is set to 1 ms/div, how many horizontal major divisions will ONE complete cycle occupy on the screen?",
      "options": [
        "4 horizontal divisions",
        "2.5 horizontal divisions",
        "250 horizontal divisions",
        "0.4 horizontal divisions"
      ],
      "correct": 0,
      "num": {
        "values": [
          4
        ],
        "unit": "divisions"
      },
      "expected": "4 horizontal divisions",
      "short": "T = 1/250 = 0.004 s = 4 ms; at 1 ms/div that is 4 divisions.",
      "solution": "### Step 1 \u2014 Period from frequency\n$$T = \\frac{1}{f} = \\frac{1}{250} = 0.004\\ \\text{s} = 4\\ \\text{ms}$$\n\n### Step 2 \u2014 Convert the period into divisions\n$$\\text{Divisions} = \\frac{T}{\\text{Time/Div}} = \\frac{4\\ \\text{ms}}{1\\ \\text{ms/div}} = 4\\ \\text{divisions}$$\n\n### Answer\n**4 horizontal divisions**\n\n### Distractor analysis\n- **2.5 divisions** \u2014 inverting the ratio ($1\\text{ ms} / 4\\text{ ms}$ style error) or mixing up\n  $f$ and $T$.\n- **250 divisions** \u2014 using the frequency number as if it were a time.\n- **0.4 divisions** \u2014 the reciprocal again, from dividing time-base by period.\n\n### Sanity check\nA 250 Hz signal with a 1 ms/div setting shows 4 cycles across a 10-division screen (40 ms total).\nIf your answer implies less than one cycle or hundreds of cycles, re-check the conversion."
    },
    {
      "id": "eee282_q27",
      "topicId": "cro-calculations",
      "kind": "calc",
      "type": "calc",
      "question": "A pure AC sine wave with an RMS voltage of 14.14 V is measured on a CRO set to 10 V/div. How many vertical divisions peak-to-peak will this wave occupy?",
      "options": [
        "4 vertical divisions peak-to-peak",
        "2 vertical divisions peak-to-peak",
        "8 vertical divisions peak-to-peak",
        "1.414 vertical divisions peak-to-peak"
      ],
      "correct": 0,
      "num": {
        "values": [
          4
        ],
        "unit": "divisions"
      },
      "expected": "4 vertical divisions peak-to-peak",
      "short": "Vp = 1.414 \u00d7 14.14 = 20 V; Vp-p = 40 V; at 10 V/div that is 4 divisions.",
      "solution": "### Step 1 \u2014 RMS to peak\nFor a sine wave, $V_p = 1.414\\,V_{rms}$:\n$$V_p = 1.414 \\times 14.14 = 20\\ \\text{V}$$\n\n### Step 2 \u2014 Peak to peak-to-peak\n$$V_{p\\text{-}p} = 2V_p = 2 \\times 20 = 40\\ \\text{V}$$\n\n### Step 3 \u2014 Voltage into divisions\n$$\\text{Divisions} = \\frac{V_{p\\text{-}p}}{\\text{Volts/Div}} = \\frac{40\\ \\text{V}}{10\\ \\text{V/div}} = 4\\ \\text{divisions}$$\n\n### Answer\n**4 vertical divisions peak-to-peak**\n\n### Distractor analysis\n- **2 divisions** \u2014 using $V_p$ (20 V) instead of $V_{p\\text{-}p}$ (40 V) in the last step.\n- **8 divisions** \u2014 using $V_{rms}\\times2 = 28.28$ V and then rounding upward, or doubling twice.\n- **1.414 divisions** \u2014 mistaking the *conversion constant* for the answer.\n\n### Note on 14.14 V\nExaminers pick 14.14 V on purpose: $14.14 \\times 1.414 \\approx 20$, a clean round number. When you\nsee 14.14 or 7.07, expect a factor of $\\sqrt{2}$ to be involved."
    },
    {
      "id": "eee282_q28",
      "topicId": "cro-calculations",
      "kind": "calc",
      "type": "calc",
      "image": "/images/eee282/q28.svg",
      "question": "A signal displayed on a CRO set to DC coupling lies entirely above the zero baseline. The positive peak is at +5 divisions and the negative trough is at +1 division. The Volts/Div knob is at 2 V/div. Calculate: (i) Vp-p, (ii) AC Peak Voltage Vp, and (iii) DC Offset Voltage.",
      "options": [
        "Vp-p = 8 V, Vp = 4 V, DC offset = 6 V",
        "Vp-p = 8 V, Vp = 4 V, DC offset = 4 V",
        "Vp-p = 12 V, Vp = 6 V, DC offset = 6 V",
        "Vp-p = 8 V, Vp = 8 V, DC offset = 6 V"
      ],
      "correct": 0,
      "num": {
        "values": [
          8,
          4,
          6
        ],
        "unit": "V"
      },
      "expected": "Vp-p = 8 V, Vp = 4 V, DC offset = 6 V",
      "short": "Vp-p = (5\u22121) div \u00d7 2 = 8 V; Vp = 4 V; DC offset = midpoint (5+1)/2 = 3 div \u00d7 2 = 6 V.",
      "solution": "### Reading the screen\nPositive peak = **+5 div**, negative trough = **+1 div**, so the wave never crosses zero \u2014 a DC\nlevel is lifting the whole sine wave.\n\n### Step 1 \u2014 Peak-to-peak\n$$V_{p\\text{-}p} = (5 - 1)\\ \\text{div} \\times 2\\ \\frac{\\text{V}}{\\text{div}} = 4 \\times 2 = 8\\ \\text{V}$$\n\n### Step 2 \u2014 AC peak\n$$V_p = \\frac{V_{p\\text{-}p}}{2} = \\frac{8}{2} = 4\\ \\text{V}$$\n\n### Step 3 \u2014 DC offset (the mean level)\nThe DC level sits midway between the two extremes:\n$$V_{DC} = \\frac{5 + 1}{2}\\ \\text{div} \\times 2\\ \\frac{\\text{V}}{\\text{div}} = 3 \\times 2 = 6\\ \\text{V}$$\n\n### Answer\n**Vp-p = 8 V, Vp = 4 V, DC offset = 6 V DC**\n\n### Distractor analysis\n- **DC offset = 4 V** \u2014 using $V_p$ as the offset. The offset is the **midpoint**, not the peak.\n- **Vp-p = 12 V** \u2014 adding the divisions (5 + 1) instead of subtracting them.\n- **Vp = 8 V** \u2014 failing to halve the peak-to-peak value.\n\n### Exam tip\nThis is exactly why you park the trace on the centre line with the coupling in **GND** before\nmeasuring: with DC coupling, \"0 V\" is not wherever the trace happens to sit."
    },
    {
      "id": "eee282_q29",
      "topicId": "cro-calculations",
      "kind": "calc",
      "type": "calc",
      "image": "/images/eee282/q29.svg",
      "question": "In a dual-trace CRO phase measurement, one complete cycle of Signal A spans 8 horizontal divisions. Signal B passes through zero exactly 1 horizontal division after Signal A. Calculate the phase shift angle between the two signals in degrees.",
      "options": [
        "45\u00b0",
        "90\u00b0",
        "30\u00b0",
        "360\u00b0"
      ],
      "correct": 0,
      "num": {
        "values": [
          45
        ],
        "unit": "degrees"
      },
      "expected": "45\u00b0",
      "short": "Phase = (1 div / 8 div) \u00d7 360\u00b0 = 45\u00b0.",
      "solution": "### The phase formula\nOne full cycle = $360^\\circ$ = the number of divisions in one period (here, 8). So:\n$$\\phi = \\frac{\\text{shift in divisions}}{\\text{divisions per cycle}} \\times 360^\\circ$$\n\n### Substitution\n$$\\phi = \\frac{1}{8} \\times 360^\\circ = 45^\\circ$$\n\n### Answer\n**45\u00b0** (Signal B lags Signal A by 45\u00b0.)\n\n### Distractor analysis\n- **90\u00b0** \u2014 assumes the shift is a quarter of a cycle (2 divisions) instead of one-eighth.\n- **30\u00b0** \u2014 a guess based on 12 divisions per cycle, not the 8 given.\n- **360\u00b0** \u2014 that is one **whole** cycle; a 1-division shift out of 8 is far smaller.\n\n### Exam tips\n- The answer is independent of the Time/Div setting \u2014 both the shift and the period are measured in\n  the **same** divisions, so the setting cancels out.\n- Only use this when **both** traces are on the same Time/Div setting (they always are on a\n  dual-trace CRO)."
    },
    {
      "id": "eee282_q30",
      "topicId": "cro-calculations",
      "kind": "calc",
      "type": "calc",
      "image": "/images/eee282/q30.svg",
      "question": "A CRO in X-Y mode displays a Lissajous pattern. A reference frequency fx = 50 Hz is applied to the X-input. The pattern shows 4 horizontal tangency points and 1 vertical tangency point. Calculate the unknown frequency fy applied to the Y-input.",
      "options": [
        "200 Hz",
        "12.5 Hz",
        "50 Hz",
        "800 Hz"
      ],
      "correct": 0,
      "num": {
        "values": [
          200
        ],
        "unit": "Hz"
      },
      "expected": "200 Hz",
      "short": "fy/fx = horizontal tangencies / vertical tangencies = 4/1, so fy = 4 \u00d7 50 = 200 Hz.",
      "solution": "### The Lissajous ratio\n$$\\frac{f_y}{f_x} = \\frac{\\text{number of horizontal tangencies}}{\\text{number of vertical tangencies}}$$\n\n### Substitution\n$$\\frac{f_y}{50} = \\frac{4}{1} \\quad\\Rightarrow\\quad f_y = 4 \\times 50 = 200\\ \\text{Hz}$$\n\n### Answer\n**200 Hz**\n\n### How to count tangencies\n- **Horizontal tangency** \u2014 count how many points the curve touches a **horizontal** line drawn\n  across the pattern (equivalently, the number of horizontal \"lobes\").\n- **Vertical tangency** \u2014 the number of points touching a **vertical** line.\nDo not count intersections with the graticule; count the **touching points on the outline** of the\nfigure.\n\n### Distractor analysis\n- **12.5 Hz** \u2014 the ratio inverted ($1/4 \\times 50$).\n- **50 Hz** \u2014 assumes equal frequencies, which would give a circle/ellipse (1:1).\n- **800 Hz** \u2014 multiplying by 16 instead of 4, usually from counting both axes' lobes together.\n\n### Exam tip\nThis method only works when the two frequencies are in a **simple integer ratio**; otherwise the\nfigure drifts and cannot be read."
    }
  ]
}
